name: "My Custom Action"
description: "This is a custom action from other_repo_test."
inputs:
  message:
    description: "A message to output"
    required: true
runs:
  using: "composite"  # 複合アクションとして実行する場合
  steps:
    - name: Echo the message
      run: echo "${{ inputs.message }}"
